export const consoleHtml = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DG-LAB WorkerHub</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#e8edf7;background:#101521}*{box-sizing:border-box}body{margin:0}header{padding:22px 6vw;background:#171e2d;border-bottom:1px solid #29354c}main{max-width:1050px;margin:auto;padding:28px 20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}.card{background:#171e2d;border:1px solid #29354c;border-radius:14px;padding:18px;margin-bottom:16px}h1,h2{margin-top:0}input,select,textarea,button{width:100%;padding:10px;margin:5px 0;border-radius:8px;border:1px solid #34415b;background:#101521;color:#e8edf7}button{background:#4d69ff;border:0;font-weight:700;cursor:pointer}.muted{color:#9aa7bd}.ok{color:#5ee49d}.bad{color:#ff8490}pre{white-space:pre-wrap;max-height:250px;overflow:auto}.row{display:flex;gap:8px}.row>*{flex:1}.device{padding:10px;border:1px solid #34415b;border-radius:8px;margin:8px 0;cursor:pointer}
</style></head><body><header><h1>DG-LAB WorkerHub</h1><span class="muted">Cloudflare Workers 设备控制台</span></header><main>
<div class="grid"><section class="card"><h2>登录</h2><input id="token" type="password" placeholder="管理 token"><button onclick="login()">Token 登录</button><p id="session" class="muted">尚未登录</p></section>
<section class="card"><h2>设备</h2><div class="row"><input id="newName" placeholder="设备名称"><button onclick="createDevice()">创建</button></div><div id="devices"></div></section></div>
<section class="card"><h2>设备详情</h2><p id="selected" class="muted">请先选择设备</p><pre id="status">{}</pre><div class="row"><input id="clientId" placeholder="clientId"><input id="targetId" placeholder="targetId"><button onclick="bind()">绑定</button><button onclick="unbind()">解绑</button></div>
<div class="row"><select id="channel"><option value="1">通道 A</option><option value="2">通道 B</option></select><select id="mode"><option value="2">设置</option><option value="1">增加</option><option value="0">减少</option></select><input id="strength" type="number" min="0" max="200" value="10"><button onclick="strength()">发送强度</button><button onclick="clearChannel()">清空</button></div>
<textarea id="pulses" placeholder='波形 JSON，例如 ["0A0A0A0A0A0A0A0A"]'></textarea><button onclick="waveform()">发送波形</button><h3>状态日志</h3><pre id="logs">[]</pre></section>
<section class="card"><h2>MCP 风格工具</h2><button onclick="mcpTools()">查看工具</button><select id="tool"><option>list_devices</option><option>get_device_status</option><option>set_strength</option><option>send_waveform</option><option>clear_channel</option><option>bind_device</option><option>unbind_device</option></select><textarea id="args" placeholder='工具参数 JSON，例如 {"deviceId":"..."}'>{}</textarea><button onclick="callTool()">测试调用</button><pre id="mcp">[]</pre></section>
<script>
let bearer=localStorage.bearer||'', deviceId=''; const out=(id,x)=>document.getElementById(id).textContent=JSON.stringify(x,null,2);
async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+bearer,'Content-Type':'application/json'};let r=await fetch(path,opt),x=await r.json();if(!r.ok)throw Error(x.error||r.statusText);return x}
async function login(){try{let x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({token:token.value})});bearer=x.session.id;localStorage.bearer=bearer;session.textContent='已登录，有效期至 '+x.session.expiresAt;session.className='ok';load()}catch(e){session.textContent=e.message;session.className='bad'}}
async function load(){try{let x=await api('/api/devices');devices.innerHTML=x.devices.map(d=>'<div class="device" onclick="selectDevice(\''+d.id+'\')"><b>'+d.name+'</b><br><span class="muted">'+d.id+'</span></div>').join('')}catch(e){session.textContent=e.message}}
async function createDevice(){await api('/api/devices',{method:'POST',body:JSON.stringify({name:newName.value})});load()}
async function selectDevice(id){deviceId=id;selected.textContent=id;refresh()} async function refresh(){if(!deviceId)return;out('status',await api('/api/devices/'+deviceId+'/status'));out('logs',await api('/api/devices/'+deviceId+'/logs'))}
async function act(path,body={}){try{out('status',await api('/api/devices/'+deviceId+'/'+path,{method:'POST',body:JSON.stringify(body)}));refresh()}catch(e){alert(e.message)}}
const bind=()=>act('bind',{clientId:clientId.value,targetId:targetId.value}),unbind=()=>act('unbind'),strength=()=>act('strength',{channel:channel.value,mode:Number(mode.value),value:Number(document.getElementById('strength').value)}),clearChannel=()=>act('clear',{channel:channel.value}),waveform=()=>act('waveform',{channel:channel.value,pulses:JSON.parse(pulses.value)});
async function mcpTools(){out('mcp',await api('/api/mcp/tools'))} async function callTool(){out('mcp',await api('/api/mcp/tool/'+tool.value,{method:'POST',body:args.value}))} load();
</script></main></body></html>`;
